File_id="$1"
File_name="$2"
Output_folder="$3"
!gdown "https://drive.google.com/uc?id=${File_id}&confirm=t"
!mkdir -p "${Output_folder}"
!unzip -q "${File_name}.zip" -d "${Output_folder}/${File_name}"