python train.py \
    --data_folder data/sample100_L160(test) \
    --output_folder output/sample(test) \
    --img_height 160 \
    --img_width 160 \
    --batch_size 6 \
    --val_batch_size 100 \
    --max_epoch 10 \
    --learning_rate 0.01 \
    --decay_epoch 2 \
    --device gpu \
    --pin_memory_train True \
    --prob True